Squashed port of ambient Now Playing container from Pixel [stripped down version]
ezio84: this is a very stripped down part of code from the original commit by Joe:
"SystemUI: Port Now Playing feature from Pixel [1/2]"
https://review.carbonrom.org/#/c/4950/
adapted to be called from StatusBar class for our local Ambient Display
music ticker.
Removed everything we don't need, services and listeners, and reparsed
everything to make it clean.

[spezi77] edits:
* Cleaned up for Android 11.
* Updated for Android 13.

[ExactExampl] squashed with following changes:

commit 64f3f4c0dc28640a38593de0c1a4ae3b07b096dc
Author: spezi77 <spezi7713@gmx.net>
Date:   Sat Jan 16 20:31:43 2021 +0100

    Ambient music ticker: show Now Playing info on lockscreen.

    [spezi77] Updated for Android 13

    abc: keep just the nowplaying part from PixelDust @spezi77 code
    and some code cleanup

    Change-Id: I51fcf831451788b758bfe59c05d424a44f444315

    ---

    for the ambient display, abc music ticker code already allows to show
    both local player and Now Playing info under the clock.

    In lockscreen, instead, the local player shows its own media
    notification, but Now Playing info are missing.

    This commit adds Now Playing to lockscreen so we can cover all cases.

    Signed-off-by: spezi77 <spezi7713@gmx.net>

commit fdf5b4c9c97f35f216d2e1b362f46e8ba1e2717a
Author: Jayant-Deshmukh <jayantdeshmuk008@gmail.com>
Date:   Sat Jan 8 13:33:22 2022 +0000

    Ambient music ticker: Show the now playing container on Ambient screen as well

    - Apparently after the whole SystemUI stub changes there is no song name displayed on Ambient pulse after Now Playing song detection.
    - Just extend the lockscreen Ambient Container to Ambient Display so we get the song name after the pulse.
    - However local track change will display the ambient ticker the traditional way (Below/Above the time)

    Signed-off-by: Jayant-Deshmukh <jayantdeshmuk008@gmail.com>
    Change-Id: Ibb1d1c8f71a3de7442821cdb9410b99c250734f6
    Signed-off-by: spezi77 <spezi7713@gmx.net>

commit 3c061243f761c7a34dcad2f31e92074106f1231c
Author: Jayant-Deshmukh <jayantdeshmuk008@gmail.com>
Date:   Fri Jan 7 06:37:08 2022 +0000

    Ambient music ticker: Fix layout on Android 12

    - Updated from SQ1D.211205.016.A1

    Signed-off-by: Jayant-Deshmukh <jayantdeshmuk008@gmail.com>
    Change-Id: Ic63dcf72a5b9130a782273725f6c7bf8615ace7d
    Signed-off-by: spezi77 <spezi7713@gmx.net>

commit e489a9acd4179dfbba7019d1333b6c2a440463d4
Author: spezi77 <spezi7713@gmx.net>
Date:   Fri Jan 14 23:54:12 2022 +0100

    Ambient music ticker: Moar layout fixes.
    The padding between the ambient indication and the locksceen icon
    was way too small. This commit will improve it to make it look
    as on the Pixel stock ROM.

    Partially taken from SQ1D.211205.016.A1

    Signed-off-by: spezi77 <spezi7713@gmx.net>
    Change-Id: I1d51f4a0df5d51e8acb3fb085cc270e914e5bf00

commit 4f53f8853090863d32f8278ba3edf1457eb6d75c
Author: spezi77 <spezi7713@gmx.net>
Date:   Thu Mar 17 22:33:39 2022 +0100

    KeyguardSliceProvider: Show NP titles in AmbientIndication only.

    Signed-off-by: spezi77 <spezi7713@gmx.net>

commit 3dee220e3d4d5fdd249a6e00f36df0d803c10562
Author: spezi77 <spezi7713@gmx.net>
Date:   Thu Mar 17 16:19:28 2022 +0100

    SystemUI: Fix NPE in AmbientIndicationContainer.

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

commit 853647acfc7257365862a0d3eb33cbd8a76771db (HEAD -> pb_alpha)
Author: spezi77 <spezi7713@gmx.net>
Date:   Mon Feb 21 17:43:56 2022 +0100

    AmbientIndication: Fix music ticker being black on AOD with light wallpaper.
    In the current implementation, if we set a light wallpaper, the
    text color of the music ticker is set to black, which is correct
    for the keyguard -- but not for AOD/Ambient display.

    This commit uses a similar check as is used in the AOSP statusbar
    to distinguish whether a light or dark wallpaper is in use.
    Of course, on AOD/ambient display the text color must always be white.

    * Updated DarkReceiver for Android 13.

    Signed-off-by: spezi77 <spezi7713@gmx.net>

Change-Id: If1c2cf233d72ed8b31bc44f9852ba7b5c1181697